#! /bin/bash

# Check that we are not being run from a snapshot and
# quit if we are.
grep -q "rd.lkg.snapshot" < /proc/cmdline && exit

# Load the RC functions (ebegin, eend, etc).
source /lib/rc/sh/functions.sh

ebegin "Last Known Good (LKG)"

/usr/sbin/lkgtests "$@" && /usr/sbin/lkg

eend $?
